# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "28e74bd37976895dd299f3df087bfe1d"
name = "pincode-validator-proo"
application_url = "https://apps.ppdesigntech.com"
embedded = true

handle = "pinsure-pincode-validator"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact"
  ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://apps.ppdesigntech.com/api/auth" ]


[app_proxy]
url = "https://apps.ppdesigntech.com/apps/pincode-validator"
subpath = "pincode-validator"
prefix = "apps"
