-- AlterTable
ALTER TABLE "AppSetting" ADD COLUMN     "locationDetectionEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "popupAutoClose" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "popupAutoCloseDelay" INTEGER NOT NULL DEFAULT 1500,
ADD COLUMN     "popupButtonText" TEXT NOT NULL DEFAULT 'Check Availability',
ADD COLUMN     "popupCloseOnOverlay" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "popupDelaySeconds" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "popupDescription" TEXT NOT NULL DEFAULT 'Enter your pincode to check delivery availability.',
ADD COLUMN     "popupEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "popupLocationText" TEXT NOT NULL DEFAULT 'Use my current location',
ADD COLUMN     "popupRemember" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "popupRememberDays" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN     "popupShowCart" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "popupShowClose" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "popupShowCollection" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "popupShowHome" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "popupShowPages" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "popupShowProduct" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "popupTheme" TEXT NOT NULL DEFAULT 'light',
ADD COLUMN     "popupTitle" TEXT NOT NULL DEFAULT 'Check Delivery Availability',
ADD COLUMN     "popupTrigger" TEXT NOT NULL DEFAULT 'delay',
ADD COLUMN     "popupWidth" INTEGER NOT NULL DEFAULT 420;
